<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net48</TargetFrameworks>
    <PlatformTarget>x86</PlatformTarget>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>STFormatter.UI</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\STFormatter.Core\STFormatter.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Drawing" />
  </ItemGroup>
</Project>