using System.Collections.Generic;

namespace STFormatter.UI
{
    public static class Strings
    {
        private static readonly Dictionary<string, string> _strings = new()
        {
            ["App.Title"] = "STBud for TwinCAT",
            ["Tray.Text"] = "STBud for TwinCAT",
            ["Tray.Settings"] = "Settings",
            ["Tray.Instances"] = "Instances",
            ["Tray.History"] = "History",
            ["Tray.Log"] = "Log",
            ["Tray.Restart"] = "Restart",
            ["Tray.Exit"] = "Exit",
            ["Tray.Saved.Title"] = "STBud for TwinCAT",
            ["Tray.Saved.Text"] = "Settings saved.",
            ["Tab.Settings"] = "Settings",
            ["Tab.Instances"] = "Instances",
            ["Tab.History"] = "History",
            ["Tab.Log"] = "Log",
            ["Tab.Toolbox"] = "Toolbox",
            ["Tray.Toolbox"] = "Toolbox",
            ["Toolbox.Group.Pinger"] = "TwinCAT Machine Pinger",
            ["Toolbox.Target"] = "Target (IP / hostname):",
            ["Toolbox.Timeout"] = "Timeout (ms):",
            ["Toolbox.Check"] = "Check",
            ["Toolbox.RunDiagnostics"] = "Run Diagnostics",
            ["Toolbox.CopyOutput"] = "Copy Output",
            ["Toolbox.Clear"] = "Clear",
            ["Settings.Preset"] = "Preset:",
            ["Settings.Preset.Default"] = "Default",
            ["Settings.Preset.Compact"] = "Compact",
            ["Settings.Preset.Expanded"] = "Expanded",
            ["Settings.Button.Preview"] = "Preview",
            ["Settings.Button.Apply"] = "Apply",
            ["Settings.Button.Reset"] = "Reset",
            ["Settings.Group.Indentation"] = "Indentation",
            ["Settings.Group.Keywords"] = "Newlines & Keywords",
            ["Settings.Group.Spacing"] = "Spacing",
            ["Settings.Group.Lines"] = "Lines & Alignment",
            ["Settings.Group.Behavior"] = "Behavior",
            ["Settings.Group.General"] = "General",
            ["Settings.IndentStyle"] = "Indent style:",
            ["Settings.IndentSize"] = "Indent size:",
            ["Settings.ContinuationIndent"] = "Continuation indent:",
            ["Settings.Newline"] = "Newline style:",
            ["Settings.KeywordCasing"] = "Keyword casing:",
            ["Settings.BraceStyle"] = "Brace style:",
            ["Settings.SpaceAroundOperators"] = "Spaces around operators",
            ["Settings.SpaceAfterComma"] = "Space after comma",
            ["Settings.SpaceBeforeSemicolon"] = "Space before semicolon",
            ["Settings.SpaceAfterColon"] = "Space after colon",
            ["Settings.AlignAssignments"] = "Align assignments",
            ["Settings.AlignDeclarations"] = "Align variable declarations",
            ["Settings.MaxLineLength"] = "Max line length:",
            ["Settings.EmptyLinesBetweenPOUs"] = "Empty lines between POUs:",
            ["Settings.EmptyLinesBetweenVarSections"] = "Empty lines between VAR sections:",
            ["Settings.KeepSingleLineBlocks"] = "Keep single-line blocks on one line",
            ["Settings.FormatOnSave"] = "Format on save",
            ["Settings.StartWithWindows"] = "Start with Windows",
            ["Settings.Language"] = "Language:",
            ["Settings.SavedAt"] = "Last saved: {0}",
            ["Settings.NeverSaved"] = "Not saved yet.",
            ["Settings.Preview.Error"] = "Preview error: {0}",
            ["Settings.ResetConfirm.Title"] = "Reset settings",
            ["Settings.ResetConfirm.Text"] = "Reset all settings to defaults?",
            ["Settings.RestartNote"] = "Language changes take effect on next start.",
            ["Instances.Refresh"] = "Refresh",
            ["Instances.Scan"] = "Scan",
            ["Instances.Cleanup"] = "Cleanup Stale",
            ["Instances.None"] = "No instances",
            ["Instances.Status.Connected"] = "Connected",
            ["Instances.Status.Disconnected"] = "Disconnected",
            ["Instances.Columns.PID"] = "PID",
            ["Instances.Columns.Title"] = "Title",
            ["Instances.Columns.Status"] = "Status",
            ["Instances.Columns.Menus"] = "Injected Menus",
            ["Instances.Columns.LastFormat"] = "Last Format",
            ["Instances.Columns.Count"] = "Format Count",
            ["History.Clear"] = "Clear History",
            ["History.Export"] = "Export Log...",
            ["History.Hint"] = "Double-click a row to open diff viewer.",
            ["History.Empty"] = "No formats yet",
            ["History.Columns.Time"] = "Time",
            ["History.Columns.PID"] = "PID",
            ["History.Columns.Title"] = "Title",
            ["History.Columns.File"] = "File",
            ["History.Columns.Section"] = "Section",
            ["History.Columns.Lines"] = "Lines",
            ["History.Columns.Method"] = "Method",
            ["History.Columns.Result"] = "Result",
            ["Log.Clear"] = "Clear",
            ["Log.CopyAll"] = "Copy All",
            ["Log.Open"] = "Open in Notepad",
            ["Log.AutoScroll"] = "Auto-scroll",
            ["Common.OK"] = "OK",
            ["Common.Cancel"] = "Cancel",
            ["Common.Yes"] = "Yes",
            ["Common.No"] = "No",
            ["Common.None"] = "-",
            ["Diff.Original"] = "Original",
            ["Diff.Formatted"] = "Formatted",
            ["Diff.ChangesOnly"] = "Changes only",
            ["Diff.NoChanges"] = "No changes.",
            ["Diff.NoInput"] = "No input.",
            ["Diff.Legend"] = "+ added   - removed   ~ changed   ... snip",
            ["Diff.Unchanged"] = "unchanged",
            ["AddMenu.WarningTitle"] = "Add Warning",
            ["AddMenu.WarningPrompt"] = "Enter warning text:",
            ["AddMenu.StartRegionTitle"] = "Start Region",
            ["AddMenu.StartRegionPrompt"] = "Enter region name:",
            ["AddMenu.StartEndRegionTitle"] = "Insert Region",
            ["AddMenu.StartEndRegionPrompt"] = "Enter region name:",
            ["AddMenu.NoExplicitCallTitle"] = "no_explicit_call",
            ["AddMenu.NoExplicitCallPrompt"] = "Enter call restriction message:",
            ["AddMenu.OpcUaDaTitle"] = "OPC.UA.DA",
            ["AddMenu.OpcUaDaPrompt"] = "Enter OPC UA DA parameter (e.g. '1'):",
            ["AddMenu.AlwaysAverageTitle"] = "always_average",
            ["AddMenu.AlwaysAveragePrompt"] = "Enter variable name for averaging:",
            ["AddMenu.ObsoleteTitle"] = "obsolete",
            ["AddMenu.ObsoletePrompt"] = "Enter deprecation message:",
            ["AddMenu.IOLinkingTitle"] = "I/O Linking",
            ["AddMenu.IOLinkingPrompt"] = "Enter I/O path (e.g. TIID^Device 1^Term 1^Channel 1^Output):",
            ["AddMenu.TaskNameTitle"] = "task_name",
            ["AddMenu.TaskNamePrompt"] = "Enter task name:",
            ["AddMenu.CallAfterTitle"] = "call_after",
            ["AddMenu.CallAfterPrompt"] = "Enter POU name (this POU is called after):",
            ["AddMenu.CallBeforeTitle"] = "call_before",
            ["AddMenu.CallBeforePrompt"] = "Enter POU name (this POU is called before):",
            ["AddMenu.CallAfterInitTitle"] = "call_after_init",
            ["AddMenu.CallAfterInitPrompt"] = "Enter POU name (called after its initialization):",
            ["AddMenu.CallBeforeInitTitle"] = "call_before_init",
            ["AddMenu.CallBeforeInitPrompt"] = "Enter POU name (called before its initialization):",
            ["AddMenu.CallAfterExitTitle"] = "call_after_exit",
            ["AddMenu.CallAfterExitPrompt"] = "Enter POU name (called after its exit):",
            ["AddMenu.CallBeforeExitTitle"] = "call_before_exit",
            ["AddMenu.CallBeforeExitPrompt"] = "Enter POU name (called before its exit):",
            ["AddMenu.PriorityTitle"] = "priority",
            ["AddMenu.PriorityPrompt"] = "Enter priority (1 = highest):",
            ["IOTree.Title"] = "Select I/O Path",
            ["IOTree.NoNodes"] = "No I/O devices found in project",
            ["IOTree.Path"] = "I/O Path:",
            ["IOTree.Device"] = "Device",
            ["IOTree.Terminal"] = "Terminal",
            ["IOTree.Channel"] = "Channel",
            ["IOTree.Input"] = "Input",
            ["IOTree.Output"] = "Output",
        };

        public static string Culture => "en";

        public static void ApplyLanguage(string culture)
        {
            // English only; no-op for any language code.
        }

        public static string Get(string key, params object[] args)
        {
            if (!_strings.TryGetValue(key, out var value))
                return key;
            if (args != null && args.Length > 0)
                return string.Format(System.Globalization.CultureInfo.CurrentCulture, value, args);
            return value;
        }
    }
}