<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <UseCodebase>true</UseCodebase>
    <IncludeAssemblyInVSIXContainer>true</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>false</IncludeDebugSymbolsInVSIXContainer>
    <IncludeDebugSymbolsInLocalVSIXDeployment>false</IncludeDebugSymbolsInLocalVSIXDeployment>
    <CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
    <CopyOutputSymbolsToOutputDirectory>true</CopyOutputSymbolsToOutputDirectory>
    <StartAction>Program</StartAction>
    <StartProgram Condition="'$(DevEnvDir)' != ''">$(DevEnvDir)devenv.exe</StartProgram>
    <StartArguments>/rootsuffix Exp</StartArguments>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <DeployExtension Condition="'$(BuildingInsideVisualStudio)' != 'true'">False</DeployExtension>
    <CreateVsixContainer Condition="'$(BuildingInsideVisualStudio)' != 'true'">True</CreateVsixContainer>

    <TargetVsixContainer>$(MSBuildProjectDirectory)\$(MSBuildProjectName).vsix</TargetVsixContainer>
  </PropertyGroup>

  <PropertyGroup>
    <_VsixObjPath>obj\$(Configuration)\$(TargetFramework)\</_VsixObjPath>
    <FileManifest Condition="'$(FileManifest)' == ''">$(_VsixObjPath)files.json</FileManifest>
    <TemplateFileManifest Condition="'$(TemplateFileManifest)' == ''">$(_VsixObjPath)templateFiles.json</TemplateFileManifest>
    <ResourceManifest Condition="'$(ResourceManifest)' == ''">$(_VsixObjPath)resources.json</ResourceManifest>
    <CtoFileManifest Condition="'$(CtoFileManifest)' == ''">$(_VsixObjPath)ctoFiles.json</CtoFileManifest>
    <CtoCacheFile Condition="'$(CtoCacheFile)' == ''">$(_VsixObjPath)mergeCto.cache</CtoCacheFile>
    <CreateTemplateManifestsCacheFile Condition="'$(CreateTemplateManifestsCacheFile)' == ''">$(_VsixObjPath)createTemplateManifests.cache</CreateTemplateManifestsCacheFile>
    <ResourcePackagesManifest Condition="'$(GenerateResourcePackages)'=='true' and '$(ResourcePackagesManifest)'==''">$(_VsixObjPath)resourcePackages.json</ResourcePackagesManifest>
    <TemplateOutputDirectory Condition="'$(TemplateOutputDirectory)' == ''">$(_VsixObjPath)</TemplateOutputDirectory>
    <CreateVsixContainerDependsOn>$(CreateVsixContainerDependsOn);GeneratePkgDef</CreateVsixContainerDependsOn>
    <CreatePkgDefAssemblyToProcess Condition="'$(CreatePkgDefAssemblyToProcess)' == ''">$(MSBuildProjectDirectory)\obj\$(Configuration)\$(TargetFramework)\$(MSBuildProjectName).dll</CreatePkgDefAssemblyToProcess>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.0.32112.339" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="17.12.2069">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.TextManager.Interop" Version="17.0.32112.339" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Design" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\STFormatter.Core\STFormatter.Core.csproj">
      <Name>STFormatter.Core</Name>
      <IncludeOutputGroupsInVSIX>BuiltProjectOutputGroup</IncludeOutputGroupsInVSIX>
      <IncludeOutputGroupsInVSIXLocalOnly>DebugSymbolsProjectOutputGroup</IncludeOutputGroupsInVSIXLocalOnly>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="source.extension.vsixmanifest">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>

  <ItemGroup>
    <VSCTCompile Include="STFormatter.vsct">
      <ResourceName>Menus.ctmenu</ResourceName>
    </VSCTCompile>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\PackageIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="Resources\PreviewImage.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
  </ItemGroup>

  <Import Project="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" Condition="'$(VSToolsPath)' != ''" />

  <Target Name="BuildVsixContainer" AfterTargets="Build">
    <CallTarget Targets="CreateVsixContainer" Condition="'$(CreateVsixContainer)' == 'true'" />
  </Target>
</Project>
